[package]
name = "wasm-add"
version = "0.1.0"
authors = ["Kyle Lin <kylejlin.us@gmail.com>"]
description = "My wasm-pack hello world."
license = "MIT"
repository = "https://github.com/kylejlin/wasm-add"
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.0"
